### ISSUE TITLE
Incompatible with webpack

### ISSUE THREAD

**Issue by morgante** [kriszyp/json-schema#59]
Due to the way in which AMD is tested for in [validate.js](https://github.com/kriszyp/json-schema/blob/master/lib/validate.js#L16), this module is incompatible with webpack. When built in a webpack environment, it causes this error:
```
define cannot be used indirect
```

I suggest switching to a more standard module test, such as [UMD](https://github.com/umdjs/umd).

**Comment by kpalmvik** [comment]
Temporary workaround in webpack.config.js using string-replace-webpack-plugin, inspired by https://github.com/webpack/webpack/issues/138#issuecomment-136567503

```javascript
var StringReplacePlugin = require('string-replace-webpack-plugin');
...
      test: /validate.js$/,
      include: /node_modules\/json-schema/,
      loader: StringReplacePlugin.replace({ // from the 'string-replace-webpack-plugin'
        replacements: [{
          pattern: /\(\{define:typeof define!="undefined"\?define:function\(deps, factory\)\{module\.exports = factory\(\);\}\}\)\./ig,
          replacement: function(match, p1, offset, string) {
            return false;
          }
        }]
      })
...
plugins: [
    ...
    new StringReplacePlugin()
  ],
```

**Comment by dukedougal** [comment]
Just spend three hours tracking this exact problem down.  Webpack is widely used it would be great if this code supported it straight out of the box.

**Comment by dukedougal** [comment]
The outcome is still that Azure is broken with Webpack.

Azure say its not their problem, Webpack seem to think everyone else needs to make their packages compatible with it instead of the other way around, and the guy behind the json-schema package appears to have no interest in making his package to work with webpack.

It's a mexican standoff in which no-one wants to do what it takes to make their software work with each other.

https://github.com/Azure/autorest/issues/734
https://github.com/webpack/webpack/issues/2101

What can be done?

**Comment by nolanlawson** [comment]
lol, this is affecting us in PouchDB too (https://github.com/pouchdb/pouchdb/issues/5312). Is it still a Mexican standoff if there are four of us? 😛

**Comment by rafaelcorreiapoli** [comment]
I'm also having this problem... any work around ?

**Comment by ForsakenHarmony** [comment]
still same issue

**Comment by ForsakenHarmony** [comment]
could you also release it, and not just fix it?

**Comment by dukedougal** [comment]
@ForsakenHarmony why so many big name packages depend on json-schema
 which has very spotty support is a real question. It seems they would be well advised to replace it or fork it.

**Comment by ForsakenHarmony** [comment]
ask them, not me

**Comment by obecny** [comment]
please release the fix

**Comment by kriszyp** [comment]
Pushed a tag and npm publish.

**Comment by elyobo** [comment]
Close issue?  Seems fine now.
