### ISSUE TITLE
BSD License Clause

### ISSUE THREAD

**Issue by Subaszh** [kriszyp/json-schema#69]
Can you please mention the version of BSD license for the module?

**Comment by anoff** [comment]
I think this was fixed with https://github.com/kriszyp/json-schema/commit/81ca359daeea643019a4ee81b7a57c06ac53d800. Do you plan to release a patch version that pushes this change into the ecosystem? Would be much appreciated :)

**Comment by hrieke** [comment]
You might want to re-open this issue;  the files links.js and validate.js have an MIT License in the header; which is fine, but certainly needs to be mentioned in the readme & package.json, etc.
If you changed those licenses to be dual licensed under BDS 3 or AFL 2.1, then you should update links.js and validate.js to state the proper license.
Thank you!

**Comment by ihbar** [comment]
Seems to be fixed by version 0.2.5, : BSD version is mentioned, and files ave been updated. 
Ticket could be closed ?
Thanks a lot for the fix.
