### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by jb-reefer** [kriszyp/json-schema#76]
https://www.npmjs.com/package/json-schema shows nearly a million downloads a day, but the last commit was roughly a year ago. 

This is also starting to show up as having a security vuln in this, latest version.

Bueller?

**Comment by philsturgeon** [comment]
@kriszyp hey Kris, life gets in the way of open source all the time, totally understand, but this repo has TEN MILLION installs a week and we should probably find it a good home, no? I'm on the JSON Schema team, used to run thephpleague.com and am pretty used to re-homing projects. 

Would you be up for chatting about sorting this out? We can keep your name plastered on the README as Alumni / Original Author / whatever. Hit me up here or on phil@stoplight.io.

**Comment by kriszyp** [comment]
I went through some of the existing outstanding PRs and merged them and
published a new version 0.2.4. I don't see any security advisories for the
project in github. Is there anything else you think should be updated in
this repo?

**Comment by philsturgeon** [comment]
@kriszyp thank you for that Kris. Whilst I genuinely appreciate the security merges and outstanding PRs, the latest draft this project supports is draft 4, but draft 7 is out. Do you have any plans to get caught up?

**Comment by kriszyp** [comment]
I've been thinking about this for a while, and the best path forward. As mentioned there are a lot of packages that depend on this package, and it seems like one of the most important services to the community is in ensuring the stability of this package, in terms of code, size, and behavior (and ensuring it remains secure and fixing any critical bugs). The existence of this package does not preclude any other packages from implementing newer versions of JSON Schema, and many have. I don't know that it is necessary for this package to take on new versions, when others have already done so, and the other existing high-quality implementations should continue to be used and encouraged. I think other packages, like moment, have done well to define themselves as "done", for other packages to take on further innovations.

I recognize the importance of the package name. And I am certainly open to other ideas for how to use, to best serve the community. But both providing stability of the existing behavior, and pointing to and encouraging the more recent and ongoing specifications and implementations at json-schema.org (for those that visit this repository) seem like reasonable ways for this package to serve the community well?

**Comment by philsturgeon** [comment]
If you can commit to fixing bugs and keeping this stable for folks who use it, and redirect people to the more modern versions through the NPM deprecate functionality, that seems like a pretty decent thing to do.
