### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonassmedegaard** [kriszyp/json-schema#83]
newest NPM release of this project is 0.2.5, but this git repository has tags only until 0.2.3.

Please tag 0.2.4 and 0.2.5 (and 0.3.0 if/when released...), to aid those wanting to correlate NPM releases with source tracking.

**Comment by kriszyp** [comment]
Ok, I pushed these tags, let me know if you see any issues with this.

**Comment by jonassmedegaard** [comment]
Quoting Kris Zyp (2021-01-02 03:46:52)
> Ok, I pushed these tags, let me know if you see any issues with this.

That was quick.  Thanks!
