### ISSUE TITLE
security bug

### ISSUE THREAD

**Issue by surayp** [kriszyp/json-schema#88]
a security vulnerability is submitted for your repo in huntr 
check report https://huntr.dev/bounties/1ae2b7d5-4b3a-4e0a-b275-e793bd57052e

**Comment by MilosPaunovic** [comment]
Can confirm, `GitHub Advisory Database` is still reporting this repo as a vulnerability, on this report: [https://github.com/advisories/GHSA-896r-f27r-55mw](https://github.com/advisories/GHSA-896r-f27r-55mw
).

**Comment by surayp** [comment]
ok.
Can you plz validate the report in huntr.dev ?

**Comment by surayp** [comment]
by going huntr.dev report url you can validate the report so that researcher can get bounty for responsible disclosure .
Here huntr.dev pays bounty to  bug-reporter for valid security bug . And it  encourage us(researcher) to report security vulnerability responsibly to open-source project .
Thanks

**Comment by surayp** [comment]
@kriszyp 
Can you plz comment here the report link that you receiived via mail from huntr.dev ? i need to see that url.
Also closing this ticket since bug is invalidated

Thaks
