### ISSUE TITLE
json-schema is vulnerable to Prototype Pollution

### ISSUE THREAD

**Issue by NicestRudeGuy** [kriszyp/json-schema#90]
### Im on the latest version. Any idea when this will be fixed or some alternatives?

![image](https://user-images.githubusercontent.com/9863419/232713957-e13d52ea-9dbf-4203-8ccb-0f4c6962f434.png)

**Comment by kriszyp** [comment]
As your screenshot says, it is fixed in 0.4.0. You may have _one_ installation of json-schema that is latest, but probably not the one used by eslint-plugin-typescript-custom-sort-keys, and you probably need to upgrade that.

**Comment by NicestRudeGuy** [comment]
@kriszyp thanks, it makes sense. Closing.
